# Generated by Django 5.0.6 on 2024-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_clergy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergy',
            name='Post',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
