# Generated by Django 5.0.6 on 2024-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_clergy_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergy',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
