# Generated by Django 5.0.6 on 2024-07-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_clergy_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='OrganisingParish',
            new_name='OrganisingDept',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
