# Generated by Django 5.0.6 on 2024-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_organisingparish_event_organisingdept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
