# Generated by Django 5.0.6 on 2024-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_todaysdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaysdate',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
