# Generated by Django 5.0.6 on 2024-07-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_todaysdate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaysdate',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
