# Generated by Django 5.0.6 on 2024-07-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_todaysdate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergy',
            name='Image',
            field=models.ImageField(default='profile.jpg', null=True, upload_to=''),
        ),
    ]
